name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}Plugin
author: ${project.organization.name}

commands:
  pluginvisualizer:
    usage: /<command>